### ISSUE TITLE
Unable to Install Package Requiring to Load sparklyr ML Model

### ISSUE THREAD

**Issue by chrisvwn** [opencpu/opencpu#290]
Hi,

I am trying to load a package into OpenCPU on Centos 7.1 with R 3.4.3. The package uses `spark` via the `sparklyr` package and needs to read in a spark model that is saved in the `inst/extdata` folder in the package. However, the error obtained seems to indicate that R is looking for the package/extdata on hdfs rather than on the disk?

The relevant parts of the package:

`api.R` the only R script in the package connects to spark and loads the saved spark models. It also has 3 API prediction functions, one for each model:

```{r}
if(!require(sparklyr))
{
  install.packages("sparklyr")
  library(sparklyr)
  spark_install()
}

if(!require(jsonlite))
{
  install.packages("rjsonlite")
  library(rjsonlite)
}

if(!require(dplyr))
{
  install.packages("dplyr")
  library(dplyr)
}

config <- sparklyr::spark_config()
sc <- sparklyr::spark_connect(master = "spark://x.x.x.x:7077", config = config)

if(!spark_connection_is_open(sc))
  stop("Startup: Unable to connect to Spark")

strTrainingData21DT <- readRDS(system.file('extdata', 'strTrainingData21DT.RDS', package = 'vdaiocpuspark'))
mdlGBT <- sparklyr::ml_load(sc, system.file('extdata', 'sparkmdlgbt.mdl', package = 'vdaiocpuspark'))
mdlRF <- sparklyr::ml_load(sc, system.file('extdata', 'sparkmdlrf.mdl', package = 'vdaiocpuspark'))
mdlDT <- sparklyr::ml_load(sc, system.file('extdata', 'sparkmdldt.mdl', package = 'vdaiocpuspark'

function1 <- function(Inputs)
{
  ...
}

.
.
.
```
The error I get:

```
[root@vdai ~]# Rscript -e 'install.packages("vdaiocpuspark_0.1.0-1.tar.gz", repos=NULL, type="source")'
Installing package into ‘/usr/lib64/R/library’
(as ‘lib’ is unspecified)
* installing *source* package ‘vdaiocpuspark’ ...
** R
** inst
** preparing package for lazy loading
**Error : org.apache.spark.sql.AnalysisException: Path does not exist: hdfs://localhost:9000/usr/lib64/R/library/vdaiocpuspark/extdata/sparkmdlgbt.mdl/metadata/part-00000;**
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:360)
	at org.apache.spark.sql.execution.datasources.DataSource$$anonfun$14.apply(DataSource.scala:348)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.TraversableLike$$anonfun$flatMap$1.apply(TraversableLike.scala:241)
	at scala.collection.immutable.List.foreach(List.scala:381)
	at scala.collection.TraversableLike$class.flatMap(TraversableLike.scala:241)
	at scala.collection.immutable.List.flatMap(List.scala:344)
	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:348)
	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:178)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:333)
	at org.apache.spark.sql.DataFrameReader.json(DataFrameReader.scala:279)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sparklyr.Invoke$.invoke(invoke.scala:102)
	at sparklyr.StreamHandler$.handleMethodCall(stream.scala:97)
	at sparklyr.StreamHandler$.read(stream.scala:62)
	at sparklyr.BackendHandler.channelRead0(handler.scala:52)
	at sparklyr.BackendHandler.channelRead0(handler.scala:14)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:336)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1294)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:343)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:911)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:131)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:643)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:566)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:480)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:442)
	at io.netty.util.concurrent.SingleThreadEventExecutor$2.run(SingleThreadEventExecutor.java:131)
	at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:144)
	at java.lang.Thread.run(Thread.java:748)

Error : unable to load R code in package ‘vdaiocpuspark’
ERROR: lazy loading failed for package ‘vdaiocpuspark’
* removing ‘/usr/lib64/R/library/vdaiocpuspark’
* restoring previous ‘/usr/lib64/R/library/vdaiocpuspark’
Warning message:
In install.packages("vdaiocpuspark_0.1.0-1.tar.gz",  :
  installation of package ‘vdaiocpuspark_0.1.0-1.tar.gz’ had non-zero exit status
```

I realize this may be more to do with installing packages that access spark but I believe the intersection of users with experience with spark and R packaging are likely to be here. Any help is appreciated.

**Comment by chrisvwn** [comment]
Sorry about this. I have found threads addressing this issue on the sparklyr github page. Closing.
